### ISSUE TITLE
歌曲名特殊字符导致下载失败

### ISSUE THREAD

**Issue by aaron-pe** [senventise/ncm_down#1]
谢谢手搓大神的工具! 很方便!

不过遇到一个问题: 歌曲名有特殊字符(比如 冒号 :)时, 虽然显示下载成功, 但是下载的文件是0 Byte. 看起来是特殊字符导致命名失败. 有否可能修复呢? 可以用这首音乐做测试: [Keyboard Concerto No. 5 in F minor, BWV1056: 2. Largo](https://music.163.com/#/song?id=27181020). 谢谢啦~

**Comment by senventise** [comment]
应该修复了，不过我手头没有Windows机器，没办法测试。
